spring.application.name=VitalCode

# --- SERVIDOR ---
server.port=8081

# --- CONFIGURACION DE LA BASE DE DATOS ---
spring.datasource.url=jdbc:mysql://localhost:3306/vitalcode
spring.datasource.username=root
spring.datasource.password=

# --- CONFIGURACION DE JPA / HIBERNATE ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true