spring.application.name=VitalCode


# --- CONFIGURACIÓN DE LA BASE DE DATOS ---
# Cambia "ejemplo_salud_db" por el nombre exacto que creaste en HeidiSQL
spring.datasource.url=jdbc:mysql://localhost:3306/vitalcode

# Tu usuario de base de datos (usualmente root)
spring.datasource.username=root

# Tu contraseña de base de datos (déjalo en blanco si no le pusiste clave al instalar)
spring.datasource.password=root

# --- CONFIGURACIÓN DE JPA / HIBERNATE ---
# Esto hace que Spring cree o actualice las tablas en tu base de datos automáticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true